[package]
name = "rastreadorweb"
version = "0.1.0"
authors = ["Fabio Braga <fabiobraga.net@gmail.com>"]
edition = "2024"

[dependencies]
clap = "2.33.3"
reqwest = { version = "0.11", features = ["json"] }
scraper = "0.12.0"
tokio = { version = "1", features = ["full"] }
